const express = require("express");
const Company = require("../models/company");
const router = express.Router();
const axios = require('axios');



//ticker, company name, currency
const companies = [
  ['MELI','MercadoLibre', 'Argentina', 'USD'],
  ['BBL','BHP Group', 'Australia', 'USD'],
  ['ABI.XMIL', 'Anheuser-Busch InBev', 'Belgium', 'Euros'],
  ['VALE3.BVMF','Vale', 'Brazil', 'Brazilian real'],
  ['JBSS3.BVMF', 'JBS', 'Brazil', 'Brazilian real'],
  ['ABX.XTSE','Barrick Gold', 'Canada', 'Canadian Dollars'],
  ['CNR.XTSE', 'Canadian National Railway', 'Canada', 'Canadian Dollars'],
  ['TRI.XTSE', 'Thomson Reuters', 'Canada', 'Canadian Dollars'],
  ['EC', 'Ecopetrol', 'Colombia', 'USD'],
  ['VWS.XCSE', 'Vestas Wind Systems', 'Denmark', 'Danish Krone'],
  ['NOKIA.XHEL', 'Nokia', 'Finland', 'Euros'],
  ['KNEBV.XHEL', 'Kone', 'Finland', 'Euros'],
  ['OR.XMIL', 'L\'Oreal', 'France', 'Euros'],
  ['LVMH.XMIL', 'LVMH Moet Hennessy Louis Vuitton', 'France', 'Euros'],
  ['TOT.XMIL', 'Total', 'France', 'Euros' ],
  ['SANF.XMIL', 'Sanofi', 'France', 'Euros' ],
  ['VOW.XFRA', 'Volkswagen', 'Germany', 'Euros' ],
  ['SAP.XMIL', 'SAP', 'Germany', 'Euros' ],
  ['ADS.XMIL', 'Adidas', 'Germany', 'Euros' ],
  ['SIE.XMIL', 'Siemens', 'Germany', 'Euros' ],
  ['BMW.XMIL', 'BMW Group', 'Germany', 'Euros' ],
  ['ALV.XMIL', 'Allianz', 'Germany', 'Euros' ],
  ['BASF.XMIL', 'BASF', 'Germany', 'Euros' ],
  ['BAY.XMIL', 'Bayer', 'Germany', 'Euros' ],
  ['TCS.XBOM', 'Tata Consultancy Services', 'India', 'Indian Rupee' ],
  ['INFY.XBOM', 'Infosys', 'India', 'Indian Rupee' ],
  ['ITC.XBOM', 'ITC', 'India', 'Indian Rupee' ],
  ['RELIANCE.XBOM', 'Reliance Industries', 'India', 'Indian Rupee'],
  ['ACN', 'Accenture', 'Ireland', 'USD'],
  ['MDT', 'Medtronic', 'Ireland', 'USD'],
  ['TEVA', 'Teva Pharmaceutical', 'Israel', 'USD'],
  ['SPOT', 'Spotify Technology', 'Sweden', 'USD'],
  ['CX', 'Cemex', 'Mexico', 'USD'],
  ['AMX', 'America Movil', 'Mexico', 'USD'],
  ['BAP', 'Credicorp', 'Peru', 'USD'],
  ['2222.XSAU', 'Saudi ARAMCO', 'Saudi Arabia', 'Saudi Riyal'],
  ['051910.XKRX', 'LG Chem', 'South Korea', 'South Korean won'],
  ['005930.XKRX', 'Samsung', 'South Korea', 'South Korean won'],
  ['TEF.XMIL', 'Telefonica', 'Spain', 'Euros'],
  ['GRFS', 'Grifols', 'Spain', 'USD'],
  ['ERIC_A.XSTO', 'Ericsson', 'Sweden', 'Swedish Krona'],
  ['NESM.XFRA', 'Nestle', 'Switzerland', 'Euros'],
  ['UBS', 'UBS', 'Switzerland', 'USD'],
  ['TSM', 'TSMC', 'Taiwan', 'USD'],
  ['TCM1.XFRA', 'Siam Cement', 'Thailand', 'Euros'],
  ['BP.XLON', 'BP', 'United Kingdom', 'British pound sterling'],
  ['LLOY.XLON', 'Lloyds Banking Group', 'United Kingdom', 'British pound sterling'],
  ['AZN.XLON', 'AstraZeneca', 'United Kingdom', 'British pound sterling'],
  ['RIO', 'Rio Tinto', 'United Kingdom', 'USD'],
  ['GSK', 'GlaxoSmithKline', 'United Kingdom', 'USD'],
  ['AAPL', 'Apple', 'United States', 'USD'],
  ['MSFT', 'Microsoft', 'United States', 'USD'],
  ['ADBE', 'Adobe', 'United States', 'USD'],
  ['CSCO', 'Cisco Systems', 'United States', 'USD'],
  ['INTC', 'Intel', 'United States', 'USD'],
  ['FB', 'Facebook', 'United States', 'USD'],
  ['GOOG', 'Google', 'United States', 'USD'],
  ['TSLA', 'Tesla', 'United States', 'USD'],
  ['ATVI', 'Activision Blizzard','United States', 'USD'],
  ['PEP', 'PepsiCo', 'United States', 'USD'],
  ['AMZN', 'Amazon', 'United States', 'USD'],
  ['IBM', 'IBM','United States', 'USD'],
  ['T', 'AT&T', 'United States', 'USD'],
  ['NKE', 'Nike','United States', 'USD'],
  ['PG', 'Proctor & Gamble', 'United States', 'USD'],
  ['JNJ', 'Johnson & Johnson', 'United States', 'USD'],
  ['SHW', 'Sherwin-Williams', 'United States', 'USD'],
  ['CAT', 'Caterpillar', 'United States', 'USD'],
  ['MMM', '3M', 'United States', 'USD'],
  ['UNP', 'Union Pacific', 'United States', 'USD'],
  ['GE', 'General Electric', 'United States', 'USD'],
  ['UPS', 'UPS', 'United States', 'USD'],
  ['DIS', 'Disney', 'United States', 'USD'],
  ['JPM', 'JP Morgan','United States', 'USD'],
  ['V', 'Visa', 'United States', 'USD'],
  ['MCD', 'McDonalds', 'United States', 'USD'],
  ['KO', 'Coca-Cola', 'United States', 'USD'],
  ['GIS', 'General Mills', 'United States', 'USD'],
  ['PFE', 'Pfizer', 'United States', 'USD'],
  ['DOW', 'Dow Chemical', 'United States', 'USD'],
  ['HD', 'Home Depot', 'United States', 'USD'],
  ['WMT', 'Walmart', 'United States', 'USD']
]
